version: '3.9'
services:
  server:
    build:
      context: ./
    ports:
      - '4000:4000'
      - '4001:4001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command:
      - nodemon
      - src/server.js
