version: '3.9'
services:
  server:
    build:
      context: ./
    ports:
      - '4000:4000'
      - '4001:4001'
    volumes:
      - .:/app
      - /app/node_modules
    command:
      - nodemon
      - --inspect=0.0.0.0:4001
      - src/server.js
